import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UKT CABANG TRENGGALEK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-lato">

          {/* awal wrapper konten utama */}
          <div className="w-full h-screen">
            {/* konten utama */}
            <div className="min-h-full w-full bg-darkBlue flex items-center justify-center">
              <div className="text-white flex flex-col items-center text-center">

                  {/* psht icon */}
                  <img className='w-32 mb-4' src="/images/psht-icon.png" alt="" />

                  {/* title */}
                  <h1 className='text-xl font-semibold mb-12'>Uji Kenaikan Tingkat Cabang Trenggalek</h1>

        </div>
            </div>
          </div>
      </div>
    </>
  )
}
